version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6380

  redis:
    image: redis:latest
    ports:
      - "6380:6380"
